### ISSUE TITLE
Events are not fired on Forge event bus

### ISSUE THREAD

**Issue by BlayTheNinth** [ModdingForBlockheads/Forbic#13]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

dev

### Mod Version

dev

### Describe the Issue

see title

**Comment by 64thParaDux** [comment]
Thank you!

**Comment by 64thParaDux** [comment]
just wondering when you were planning to commit this stuff so I can notify my network when the server should be up.
