### ISSUE TITLE
Balm crashes when only mod installed on Forge above v39.0.59

### ISSUE THREAD

**Issue by nanonestor** [ModdingForBlockheads/Forbic#14]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.75

### Mod Version

balm-2.4.2+0.jar

### Describe the Issue

Balm library mod crashes on Forge above 39.0.59 (from my testing).

It still crashes on the latest current Forge as of this date 39.0.75.  It looks like it could be because an outdated version of mixins is being used.

Many other mods are starting to require Forge above 39.0.66 - meaning any sizeable modpacks that want those mods will need to chose either remove those or remove your mods that depend on balm until this is fixed.

### Logs

The below log is the result of a blank Forge 36.0.75 profile with balm-2.4.2+0.jar in the mods folder only.

https://paste.gg/p/anonymous/06c69281c2564b12b2da46d25ef0b9fc

**Comment by Wolferencz** [comment]
From my testing balm library mod crashes on Forge above 39.0.66
