### ISSUE TITLE
(Non-fatal) Error message in console

### ISSUE THREAD

**Issue by brnbrd** [ModdingForBlockheads/Forbic#15]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.88

### Mod Version

2.4.3+0

### Describe the Issue

Error in console

### Logs

https://pastebin.com/FwBCKxg5

**Comment by brnbrd** [comment]
Forgot to mention, this is on a dedicated server.

**Comment by BlayTheNinth** [comment]
This was most likely fixed by https://github.com/ModdingForBlockheads/Balm/commit/e6adc6262a761df52dc304954c9a80b70bde36d3 and should no longer happen on newer Balm versions.
