### ISSUE TITLE
1.18.2 Crash

### ISSUE THREAD

**Issue by ghost** [ModdingForBlockheads/Forbic#17]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

10.2, 13.3, 1.18.2

### Mod Version

1.18.2

### Describe the Issue

Balm is causing a crash due to not being updated to 1.18.2.

**Comment by ENTPRESTIGIOUS** [comment]
Ayy same issue LUL!
https://github.com/ModdingForBlockheads/Balm/issues/16

**Comment by BlayTheNinth** [comment]
Duplicate of #16 and not a bug, my mods have not been updated to 1.18.2 yet.
