### ISSUE TITLE
Crash on game startup (older version of Forge)

### ISSUE THREAD

**Issue by n0proxy** [ModdingForBlockheads/Forbic#2]
### Minecraft Version

1.17

### Mod Loader

Forge

### Mod Loader Version

37.0.65

### Mod Version

1.7.0 (also happens on 1.6.0)

### Describe the Issue

I'm using a slightly older version of Forge in order to run the Optifine preview that's compatible with 1.17.1 + Forge, so I don't know if a compatibility fix here is impossible or maybe just beyond the scope of your work.

When first setting up my server/mod pack, I realized that the newest versions of Balm would crash on the slightly older version of Forge I'm using, so I went back several versions until I found a pair of Balm+Waystones versions that would work; we used Balm 1.5.2 and Waystones 8.3.1 for a few weeks with no crashes. However, we finally got around to crafting our first Waystone yesterday, and quickly realized that the config options didn't seem to be working (no inv button to replace Warpstones and a few other things). I've seen the update notes on newer versions of Waystones/Balm and know this has been fixed in those versions.

However, the newer versions crash the game on startup when running Forge 37.0.65. I've tested Balm and Waystones alone, with no other mods (and no Optifine), and get a crash on startup with both Balm 1.7.0 and 1.6.0. I've attached an image of the crash screen, and a pastebin link to the crash log.

![image](https://user-images.githubusercontent.com/46941718/140212937-b580c156-ecc4-4559-aaa8-fd8d3226d7ff.png)

### Logs

https://pastebin.com/vNLDMScq

**Comment by BlayTheNinth** [comment]
The mod depends on a Forge feature that was only added in more recent Forge versions.
