### ISSUE TITLE
balm.mixins.json:ModelLayersAccessor No candidates were found matching ALL_MODELS:Ljava/util/Set;

### ISSUE THREAD

**Issue by CebbyS** [ModdingForBlockheads/Forbic#23]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.6

### Mod Version

3.1.0+0

### Describe the Issue

I am creating compatibility for Refabricated Slabs and KleeSlabs mod.

When running the project in IntelliJ IDEA Debug mode the exception appears: **Could not execute entrypoint stage 'client' due to errors**.

Mods used:
- Cloth-Config: 6.2.62
- KleeSlabs: 1.1.11
- ModMenu: 3.0.1
- Balm: 3.1.0+0

Please ask if and what additional information is required.

Kind regards!

### Logs

https://pastebin.com/wC67NUny

**Comment by BlayTheNinth** [comment]
In #32 which was a similar issue this resolved itself and was deemed to potentially be some caching error, maybe it's the same here?
