### ISSUE TITLE
Minecraft Client crashes caused by balm

### ISSUE THREAD

**Issue by rsta79** [ModdingForBlockheads/Forbic#28]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

41.0.98

### Mod Version

4.4.0

### Describe the Issue

This error can be caused by Forge API breaking updates,
Minecraft client crashes before showing loading screen

### Logs

java.lang.ExceptionInInitializerError: null 	at net.minecraft.client.Minecraft.handler$zem000$run(Minecraft.java:4813) ~[client-1.19-20220607.102129-srg.jar%23171!/:?] 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java) ~[client-1.19-20220607.102129-srg.jar%23171!/:?] 	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23171!/:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.98.jar%2393!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.getModEventBus()" because the return value of "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.get()" is null 	at net.blay09.mods.balm.forge.world.ForgeBalmWorldGen.<init>(ForgeBalmWorldGen.java:63) ~[balm-4.4.0.jar%23144!/:4.4.0] 	at net.blay09.mods.balm.forge.ForgeBalmRuntime.<init>(ForgeBalmRuntime.java:53) ~[balm-4.4.0.jar%23144!/:4.4.0] 	at net.blay09.mods.balm.forge.ForgeBalmRuntimeFactory.create(ForgeBalmRuntimeFactory.java:9) ~[balm-4.4.0.jar%23144!/:4.4.0] 	at net.blay09.mods.balm.api.BalmRuntimeSpi.create(BalmRuntimeSpi.java:9) ~[balm-4.4.0.jar%23144!/:4.4.0] 	at net.blay09.mods.balm.api.Balm.<clinit>(Balm.java:25) ~[balm-4.4.0.jar%23144!/:4.4.0] 	... 16 more

**Comment by BlayTheNinth** [comment]
Need the full log, this is a followup error caused by something breaking earlier in the loading process

**Comment by rsta79** [comment]
I found out that this error is caused by another mod
