### ISSUE TITLE
Crash upon start

### ISSUE THREAD

**Issue by efffauw** [ModdingForBlockheads/Forbic#3]
### Minecraft Version

1.17

### Mod Loader

Fabric

### Mod Loader Version

0.11.7

### Mod Version

1.8.0

### Describe the Issue

Game crashed upon start. Downgrading the mod fixes it

### Logs

https://www.toptal.com/developers/hastebin/iliposutov.yaml

**Comment by BlayTheNinth** [comment]
Waystones version is outdated
