### ISSUE TITLE
Requires "cloth-config2"

### ISSUE THREAD

**Issue by RogueSnowMan** [ModdingForBlockheads/Forbic#30]
### Minecraft Version

1.19.x

### Mod Loader

Fabric

### Mod Loader Version

MultiMC 5 - Version 0.6.16-3431

### Mod Version

balm-fabric-4.3.0+0

### Describe the Issue

[main/WARN]: Mod resolution failed
[main]: Immediate reason: [HARD_DEP_NO_CANDIDATE balm-fabric 4.3.0+0 -depends cloth-config2 @ [>=5.0.34]-, ROOT_FORCELOAD_SINGLE balm-fabric 4.3.0+0]
[main]: Reason: [HARD_DEP balm-fabric 4.3.0+0 -depends cloth-config2 @ [>=5.0.34]-, HARD_DEP netherportalfix 10.0.0 -depends cloth-config2 @ [>=5.0.34]-]
[main]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, gbfabrictools, fabric-textures-v0, modmenu, fabric-screen-api-v1, cloth-scissors-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, fabric-models-v0, fabric-rendering-v0, fabric-key-binding-api-v1, fabric-rendering-v1]
[main]: Fix: add [add:cloth-config2 5.0.34 ([[5.0.34,∞)])], remove [], replace []
[main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
     - Install cloth-config2, version 5.0.34 or later.
Unmet dependency listing:
     - Mod 'Balm' (balm-fabric) 4.3.0+0 requires version 5.0.34 or later of cloth-config2, which is missing!
     - Mod 'NetherPortalFix' (netherportalfix) 10.0.0 requires version 5.0.34 or later of cloth-config2, which is missing!

**Comment by BlayTheNinth** [comment]
https://www.curseforge.com/minecraft/mc-mods/cloth-config

**Comment by RogueSnowMan** [comment]
cheers, i'll try it and let you know if there are still issues

**Comment by RogueSnowMan** [comment]
So, it worked but caused another issue, not sure what though, don't know if it's an issue directly with your mod

lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: rea
derIndex(34) + length(4) exceeds writerIndex(34): PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34)

**Comment by RogueSnowMan** [comment]
correction, still no luck, still get the same crash message

**Comment by BlayTheNinth** [comment]
full logs

**Comment by RogueSnowMan** [comment]
[latest.log](https://github.com/ModdingForBlockheads/Balm/files/9125465/latest.log)


it loads fine but now, which is weird but players can't connect, if it's a conflict with another mod, let me know and i'll look at removing it, thank you for any and all help

**Comment by BlayTheNinth** [comment]
Does it happen with only Balm, NetherPortalFix and Cloth Config installed?

**Comment by RogueSnowMan** [comment]
yes, once they are removed, it boots up fine and players can log in fine

**Comment by BlayTheNinth** [comment]
Does it happen with **only Balm, NetherPortalFix and Cloth Config** installed? The question isn't "does it work if they're removed". The goal is finding out if it's truly an issue on this side or if another mod in the pack is causing a conflict.
