### ISSUE TITLE
[1.18.2] Conflict with Create 0.5c preventing loading

### ISSUE THREAD

**Issue by itsdinkd** [ModdingForBlockheads/Forbic#33]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Mod Version

3.2.0

### Describe the Issue

Updating to create 0.5c and having balm is causing loading to be infinite once launching the game. looks like resources are breaking. This is on Another Quality Modpack 2 on update I'm working on.

https://github.com/Fabricators-of-Create/Create/issues/508

### Logs

https://gist.github.com/itsdinkd/17d6d03de0e01e697413d0d93c80992a

**Comment by itsdinkd** [comment]
Downgrading Balm to 3.1.0 and removing cooking for blocklheads allowed the pack to load with no resource errors

**Comment by BlayTheNinth** [comment]
Issue in Create that's being fixed in the next version
