### ISSUE TITLE
Crash mentioning balm mixin

### ISSUE THREAD

**Issue by Atlantispy** [ModdingForBlockheads/Forbic#35]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.80

### Mod Version

3.2.0

### Describe the Issue

Loaded into pre-existing world.
In pause menu, and try to press button. 
Game freeze and crash..

Have lots of mods so apologies if not Balm, just the crash report mentioned it.

### Logs

https://pastebin.com/s4PihEmr

**Comment by darthvader45** [comment]
Had this happen on world creation too.

https://paste.ee/p/JCgri

**Comment by BlayTheNinth** [comment]
This has been fixed in Balm 3.2.1

**Comment by darthvader45** [comment]
Thank you.
