### ISSUE TITLE
[Forge Dev Env only] Mixin apply failed balm.mixins.json:CropBlockMixin -> net.minecraft.world.level.block.CropBlock

### ISSUE THREAD

**Issue by DancerVlt69** [ModdingForBlockheads/Forbic#38]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

43.1.47

### Mod Version

4.5.3 - 1.19x

### Describe the Issue

MC/Forge(/Intelli IDEA) crashes with this error/s

Mixin apply failed balm.mixins.json:CropBlockMixin -> net.minecraft.world.level.block.CropBlock

InvalidInjectionException: Critical injection failure: @Inject annotation on mayPlaceOn could not find any targets matching 

### Logs

https://gist.github.com/DancerVlt69/e192b22bba8f5ef7828eb234694fe4f1

**Comment by FibreTTP** [comment]
Seeing this on Quilt too. Removing all Balm and its dependants fixes it.

**Comment by BlayTheNinth** [comment]
Same as #32, although there it magically resolved itself. This is not the same issue as the Quilt one, as this one only happens in dev environments and seems to be mappings related rather than an injection conflict.
