### ISSUE TITLE
I need help if Balm mod is making Minecraft crash with Optifine. 

### ISSUE THREAD

**Issue by mysticetus09** [ModdingForBlockheads/Forbic#49]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

1.18.2-forge-40.1.93

### Mod Version

1.18.2

### Describe the Issue

[crash-2023-01-24_20.19.24-server.txt](https://github.com/TwelveIterationMods/Balm/files/10489466/crash-2023-01-24_20.19.24-server.txt)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

OptiFine_1.18.2_HD_U_H7

**Comment by BlayTheNinth** [comment]
Nothing in that log points towards Balm, but it's also using an outdated version of both Forge and Balm. Try updating to the latest  versions for 1.18.2.
