### ISSUE TITLE
Invalid config value for exampleCategory.exampleFloat

### ISSUE THREAD

**Issue by Starwarsfan2099** [ModdingForBlockheads/Forbic#54]
### Minecraft Version

1.20.x

### Mod Loader

Forge

### Mod Loader Version

14.1.0

### Mod Version

waystones-forge-1.20-14.0.1

### Balm Version

balm-forge-1.20-7.0.4

### Describe the Issue

A warning relating to `balm-common.toml` is constantly getting spammed at about once every five seconds.

```
[19:51:44] [Thread-1/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file /Users/username/Library/Application Support/minecraft/config/balm-common.toml is not correct. Correcting
[19:51:44] [Thread-1/ERROR] [ne.bl.mo.ba.fo.co.ForgeBalmConfig/]: Invalid config value for exampleCategory.exampleFloat, expected float but got class java.lang.Double
```

**Comment by Silvertide7** [comment]
Can confirm, I get this constantly on 1.20. It keeps generating `balm-common-#.toml.bak` files as well. I installed this because it is a dependency of Client Tweaks if that helps at all.

**Comment by Mango-Ataulfo** [comment]
Tengo el mismo error, si te sirve de algo yo no uso optifine pero si uso (oculus-mc1.20-1.6.4, rubidium-0.6.5 y TextruesRubidiumOptions-1.0.0+mc1.20) en la versión 1.20.1 de minecraft

**Comment by beowuff** [comment]
Same here. Let me know if there's anything I can test. This is breaking both kleeslabs and nether portal fix. I'm running 1.21.1

**Comment by BlayTheNinth** [comment]
> Same here. Let me know if there's anything I can test. This is breaking both kleeslabs and nether portal fix. I'm running 1.21.1

How is it breaking those mods? This should only be an error in the log + backup config files for Balm.
