### ISSUE TITLE
Modrinth Launcher and Balm (+Waystones) on 1.20.2 not working

### ISSUE THREAD

**Issue by NichtWolfi** [ModdingForBlockheads/Forbic#58]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.22

### Mod Version

7.1.4+fabric-1.20.1

### Balm Version

7.1.4

### Describe the Issue

Fresh install of Minecraft 1.20.2 with **Modrinth App**, **Fabric API** and latest **Balm** version. I noticed it after I tried to use Waystones in my survival gameplay (with other mods), but Balm doesn't work with Modrinth App and 1.20.2 on its own. The game does not start at all.

> [16:49:41] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.22
> [16:49:41] [main/INFO]: Loading 54 mods:
> 	- balm-fabric 7.1.4
> 	- fabric-api 0.89.2+1.20.2
> 	   |-- fabric-api-base 0.4.32+fce67b32a0
> 	   |-- fabric-api-lookup-api-v1 1.6.40+fce67b32a0
> 	   |-- fabric-biome-api-v1 13.0.11+86b12645a0
> 	   |-- fabric-block-api-v1 1.0.11+73761d2ea0
> 	   |-- fabric-block-view-api-v2 1.0.0+73761d2ea0
> 	   |-- fabric-blockrenderlayer-v1 1.1.42+f4b7e424a0
> 	   |-- fabric-client-tags-api-v1 1.1.3+86b12645a0
> 	   |-- fabric-command-api-v1 1.2.35+f71b366fa0
> 	   |-- fabric-command-api-v2 2.2.14+86b12645a0
> 	   |-- fabric-commands-v0 0.2.52+df3654b3a0
> 	   |-- fabric-containers-v0 0.1.71+df3654b3a0
> 	   |-- fabric-content-registries-v0 5.0.3+0ba8e9cea0
> 	   |-- fabric-convention-tags-v1 1.5.6+f4b7e424a0
> 	   |-- fabric-crash-report-info-v1 0.2.19+f4b7e424a0
> 	   |-- fabric-data-generation-api-v1 13.1.1+bbae80faa0
> 	   |-- fabric-dimensions-v1 2.1.55+b1229956a0
> 	   |-- fabric-entity-events-v1 1.5.24+f4b7e424a0
> 	   |-- fabric-events-interaction-v0 0.6.8+daef22a2a0
> 	   |-- fabric-events-lifecycle-v0 0.2.67+df3654b3a0
> 	   |-- fabric-game-rule-api-v1 1.0.39+f4b7e424a0
> 	   |-- fabric-item-api-v1 2.1.31+43511215a0
> 	   |-- fabric-item-group-api-v1 4.0.12+f4b7e424a0
> 	   |-- fabric-key-binding-api-v1 1.0.37+f4b7e424a0
> 	   |-- fabric-keybindings-v0 0.2.35+df3654b3a0
> 	   |-- fabric-lifecycle-events-v1 2.2.25+3bafade3a0
> 	   |-- fabric-loot-api-v2 2.0.1+0ba8e9cea0
> 	   |-- fabric-message-api-v1 6.0.0+fce67b32a0
> 	   |-- fabric-mining-level-api-v1 2.1.53+f4b7e424a0
> 	   |-- fabric-model-loading-api-v1 1.0.4+f4b7e424a0
> 	   |-- fabric-models-v0 0.4.3+9386d8a7a0
> 	   |-- fabric-networking-api-v1 3.0.7+74a33ae7a0
> 	   |-- fabric-object-builder-api-v1 12.1.0+b1b4f7b0a0
> 	   |-- fabric-particles-v1 1.1.3+f4b7e424a0
> 	   |-- fabric-recipe-api-v1 2.0.4+43511215a0
> 	   |-- fabric-registry-sync-v0 4.0.2+34a3e0e2a0
> 	   |-- fabric-renderer-api-v1 3.2.0+2034447ca0
> 	   |-- fabric-renderer-indigo 1.5.0+2034447ca0
> 	   |-- fabric-renderer-registries-v1 3.2.47+df3654b3a0
> 	   |-- fabric-rendering-data-attachment-v1 0.3.38+73761d2ea0
> 	   |-- fabric-rendering-fluids-v1 3.0.29+f4b7e424a0
> 	   |-- fabric-rendering-v0 1.1.50+df3654b3a0
> 	   |-- fabric-rendering-v1 3.0.9+86b12645a0
> 	   |-- fabric-resource-conditions-api-v1 2.3.8+43511215a0
> 	   |-- fabric-resource-loader-v0 0.11.10+86b12645a0
> 	   |-- fabric-screen-api-v1 2.0.10+0ba8e9cea0
> 	   |-- fabric-screen-handler-api-v1 1.3.37+86b12645a0
> 	   |-- fabric-sound-api-v1 1.0.13+f4b7e424a0
> 	   |-- fabric-transfer-api-v1 3.3.7+109a65e5a0
> 	   \-- fabric-transitive-access-wideners-v1 5.0.2+fce67b32a0
> 	- fabricloader 0.14.22
> 	- java 17
> 	- minecraft 1.20.2
> [16:49:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
> [16:49:45] [main/INFO]: Compatibility level set to JAVA_17
> [16:49:53] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 181 milliseconds
> [16:49:57] [Render thread/ERROR]: Minecraft has crashed!
> net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_465 failed
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
> Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_465 failed
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.2-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
> 	... 2 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.2-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
> 	... 2 more
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method renderBackground(Lnet/minecraft/class_332;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in balm.mixins.json:AbstractContainerScreenMixin from mod balm-fabric failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap balm-fabric-1.20.1-refmap.json
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.2-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
> 	... 2 more

### Logs

[_Log_](https://mclo.gs/nRbiWfu)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no other mods

**Comment by BlayTheNinth** [comment]
Balm has not yet been released for 1.20.2. Mods are expected to not work on newly released versions until they update.
