### ISSUE TITLE
Game Crash with exit code -1073740791

### ISSUE THREAD

**Issue by WillTereika** [ModdingForBlockheads/Forbic#60]
### Minecraft Version

1.20.x

### Mod Loader

Forge

### Mod Loader Version

48.0.33

### Mod Version

1.20.2-8.0.1

### Balm Version

8.0.1

### Describe the Issue

When starting the game, after doing ANYTHING from trying to move, break a log, ect, the game will crash nearly immediately with this error:  The game crashed whilst exception in server tick loop
Error: java.lang.NoClassDefFoundError: net/minecraftforge/common/util/FakePlayer

Full Crash Log added below.

[crash-2023-10-26_20.18.00-server.txt](https://github.com/TwelveIterationMods/Balm/files/13183866/crash-2023-10-26_20.18.00-server.txt)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Embeddium

**Comment by BlayTheNinth** [comment]
Downgrade Forge to version 48.0.14.
