### ISSUE TITLE
Support for common Fabric energy providers

### ISSUE THREAD

**Issue by BlayTheNinth** [ModdingForBlockheads/Forbic#67]
- [ ] Modern Industrialization: EU/t
- [ ] Tech Reborn: E/t
- [ ] Powah!: Fe/T
- [ ] Industrial Revolution: LF/tick
- [ ] Create Crafts and Additions

**Comment by Linguardium** [comment]
all of those support Reborn Energy API https://github.com/TechReborn/Energy
Should be simple enough to implement support for that and implicitly work with the rest
