### ISSUE TITLE
Crash upon clicking Singleplayer on screen and loading world creator due to none existing

### ISSUE THREAD

**Issue by SetOfAllSets** [ModdingForBlockheads/Forbic#70]
### Minecraft Version

1.20.4

### Mod Loader

Forge

### Mod Loader Version

Fabric 0.15.3

### Mod Version

Multiple mods

### Balm Version

9.0.3+fabric-1.20.4

### Describe the Issue

Upon clicking singleplayer and it loading the world creator (due to no pre-existing worlds) the game crashes.

### Logs

https://mclo.gs/OWqyWFV

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

I use many performance enchancing mods including sodium & friends

**Comment by minelolpride** [comment]
Reproduced on Fabric 0.15.3 for 1.20.4.
Balm 9.0.3 & Fabric API 0.92.0 are the only mods loaded.
https://mclo.gs/SrAo0Ie
