### ISSUE TITLE
Enchantment Tweaks incompatibility

### ISSUE THREAD

**Issue by allChuu** [ModdingForBlockheads/Forbic#72]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Mod Loader Version

Latest

### Mod Version

Latest

### Balm Version

Latest

### Describe the Issue

Hello,

Run into a luanch issue, the game does not launch, no fabric windows with information. Directly an Minecraft launcher error code.

I report the issue there also : https://github.com/kpzip/Enchanting-Tweaks/issues/17

### Logs

https://github.com/kpzip/Enchanting-Tweaks/issues/17

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Yes - Iris and all the company - no problem - not related.

**Comment by BlayTheNinth** [comment]
Enchantment Tweaks is using `@Overwrite`, which is a very aggressive mixin that inherently comes at the risk of breaking compatibility with other mods. This needs to be resolved on their side.

**Comment by BlayTheNinth** [comment]
Closing since this needs to be fixed on their side.
