### ISSUE TITLE
support for 1.20.6

### ISSUE THREAD

**Issue by NotAGanesh** [ModdingForBlockheads/Forbic#78]

**Comment by BlayTheNinth** [comment]
Please don't create issues for new Minecraft versions. I am aware of new releases and will port my mods when I have time and deem it appropriate (i.e. things appear stable enough).

If you'd like to be notified about releases, you can instead follow the projects on CurseForge or Modrinth, or join our [Discord](https://discord.gg/VAfZ2Nau6j).

**Comment by NotAGanesh** [comment]
@BlayTheNinth i'm extremely sorry
