### ISSUE TITLE
Game Crash on Startup

### ISSUE THREAD

**Issue by CaptConrad** [ModdingForBlockheads/Forbic#82]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.2.32

### Mod Version

7.3.3

### Balm Version

7.3.3

### Describe the Issue

I try to open the game and it just crashes. Crash screen says it's a mixin issue.

[crash-2024-06-03_16.03.15-client.txt](https://github.com/user-attachments/files/15539079/crash-2024-06-03_16.03.15-client.txt)

**Comment by vizthex123** [comment]
Same issue here. Downgrading to 7.2.2 fixes it.

Here's my log:
[latest.log](https://github.com/user-attachments/files/15539205/latest.log)

**Comment by ghost** [comment]
Just came on over to report this. Glad I'm not alone :D

Looking over vizthex123's log, it's indeed the same mixin/AT splat that I'm seeing, so I won't spam logs/crash reports, though I can post them with mixin debugging enabled if that'd help.

**Comment by Wolbobus** [comment]
YES! Yeah I'm having the same dealio.

**Comment by DavidTSF** [comment]
Im having the same error too.

**Comment by vizthex123** [comment]
> Just came on over to report this. Glad I'm not alone :D
> 
> Looking over vizthex123's log, it's indeed the same mixin/AT splat that I'm seeing, so I won't spam logs/crash reports, though I can post them with mixin debugging enabled if that'd help.

just vizthex (some guy stole me name and GitHub won't give it to me >:{), but yeah I noticed the mixin error too. Took a bit of testing to find out which mod i'd updated was causing it lol.

**Comment by dlvkvn** [comment]
After updating this mod, my game start crash on launch. 
[crash-2024-06-04_06.33.55-client.txt](https://github.com/user-attachments/files/15540790/crash-2024-06-04_06.33.55-client.txt)

**Comment by Thunderrock424242** [comment]
got the same issue i think 
[latest.log](https://github.com/user-attachments/files/15541005/latest.log)

**Comment by vizthex123** [comment]
**Update:** I updated Forge (from 47.2.6 to 47.3.0) and that didn't fix it.

**Comment by BlayTheNinth** [comment]
Fixed in Balm 7.3.4.

**Comment by dlvkvn** [comment]
Thank you!

**Comment by dlvkvn** [comment]
> Fixed in Balm 7.3.4.

Thank you!
