### ISSUE TITLE
enchancement incompatibilityy cant sneak or sprint

### ISSUE THREAD

**Issue by ImBehinYa** [ModdingForBlockheads/Forbic#83]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

latest

### Balm Version

7.3.4

### Describe the Issue

cant sprint or shift when using https://modrinth.com/mod/balm and https://modrinth.com/mod/enchancement

**Comment by BlayTheNinth** [comment]
Please provide the full logs. You can find the logs in the `logs` directory of the client or server. Most of the time `latest.log` is the correct file (unless the crash or issue happened during an earlier run).

Logs can be uploaded here by dragging the file into the comment field, or you can post them on a site like https://gist.github.com/ or https://pastebin.com/. Make sure they are set to be `public` (or unlisted) and to `never expire`.

**Comment by ImBehinYa** [comment]
okay, Hardcore rivaval breaks it balm and just [enchancement](https://modrinth.com/mod/enchancement) is no problem as soon you add hardcore revival icant sneak or shift

https://pastebin.com/ZMLj1NTs

should i reopen in hardcore rivival?

**Comment by BlayTheNinth** [comment]
Cannot reproduce, I can sneak and sprint just fine with Balm 7.3.4 and Hardcore Revival 12.0.4.

Check your controls and if you use Crafting Tweaks or Inventory Essentials, make sure they are on the latest version as well.

**Comment by ImBehinYa** [comment]
But with https://modrinth.com/mod/enchancement it doesn't work

**Comment by BlayTheNinth** [comment]
That's because Enchancement adds key mappings that default to Left Shift and Left Control. Vanilla does not support that by default and the implementation to make it work is on Enchancement's side, so this is something you have to report to them.
