### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by ashton727** [ModdingForBlockheads/Forbic#85]
### Minecraft Version

1.21

### Mod Loader

NeoForge

### Mod Loader Version

21.0.46

### Mod Version

21.0.11

### Balm Version

21.0.11

### Describe the Issue

1. Start neoforge 21.0.46 server with balm
2. Observe crash

### Logs

https://pastebin.com/4asPjjkH

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no

**Comment by BlayTheNinth** [comment]
Try Java 21

**Comment by ashton727** [comment]
This version of Neoforge requires Java 22 I believe.

**Comment by BlayTheNinth** [comment]
Minecraft 1.21 uses Java 21 and the error you're getting is because Mixin cannot load the JRE 22 (file major version 66) classes.

**Comment by ashton727** [comment]
Realized its been running on 21 the whole time. Still crashes on startup.

**Comment by BlayTheNinth** [comment]
> [01Jul2024 19:25:17.473] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: JVM identified as Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 22.0.1+8-16
[01Jul2024 19:25:17.475] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 11.0.3+main.0f24dec3 starting: java version 22.0.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
