### ISSUE TITLE
Rendering crash with balm-fabric:milk in a TechReborn cell

### ISSUE THREAD

**Issue by SubordinalBlue** [ModdingForBlockheads/Forbic#94]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

7.3.7

### Balm Version

7.3.7 (how is this question different than the previous?)

### Describe the Issue

AoF7 updated to Balm 7.3.7 and now we get a rendering crash in REI, on a TR cell with `balm-fabric:milk`

Crash does not happen with Balm 7.3.6.

Further discussion, including a crash log, on the AOE discord: https://discord.com/channels/570630340075454474/1273504044916408320

**Comment by SubordinalBlue** [comment]
> Further discussion, **including a crash log**, on the AOE discord: https://discord.com/channels/570630340075454474/1273504044916408320

But, ok:

https://pastebin.com/LW7cNpXC

**Comment by SubordinalBlue** [comment]
The further discussion already linked include a player confirming it was not other liquids in TR cells, and that the crash didn't happen with the previous version of Balm.

**Comment by BlayTheNinth** [comment]
This is an issue in Tech Reborn. `FluidRenderHandlerRegistry.INSTANCE.get` is explicitly `@Nullable` but TechReborn is [not checking for null](https://github.com/TechReborn/TechReborn/blob/1.20/src/client/java/techreborn/client/render/BaseDynamicFluidBakedModel.java#L82), resulting in the crash above.

**Comment by SubordinalBlue** [comment]
Hmm. True on surface, but wondering why it's only balm-fabric:milk and not the other ~20 give or take different mods providing fluids listed in TR cells in REI (in AoF7) that seems to be leaving that null.

(screen shot from AoF7 with Balm rolled back one version. Yes, ik, one can't see what fluids are in there from this shot; you'll have to trust me on that)

<img width="385" alt="Screenshot 2024-08-16 at 3 12 25 AM" src="https://github.com/user-attachments/assets/bf4b9ccb-03e9-4fa6-8d65-635d39567884">

[ edited for a darker screen shot ]

**Comment by SubordinalBlue** [comment]
> ~~True on surface,~~

After talking it over with a more knowledgabe acquaintance... wouldn't that really be TR not handling the null and forcing the caller to deal with it?
Shouldn't Balm be registering a default render handler for `balm-fabric:milk`?

**Comment by BlayTheNinth** [comment]
Balm could register a render handler (and will, since it's just a one-liner), but there may always be other mods who just needed a quick dummy fluid and didn't bother with its rendering.

Therefore this is absolutely also something that should be fixed in Tech Reborn as well.
