### ISSUE TITLE
Actions with same keybinds don't work

### ISSUE THREAD

**Issue by DiamondJMS** [ModdingForBlockheads/Forbic#98]
Fabric 1.20.1 v0.16.5
Balm v7.3.9

I made a modpack with forgiving void and enchancement, among other mods, and because enchancement uses shift and ctrl for some of its enchantments, running and sneaking is just disabled unless you change the keybinds.

**Comment by BlayTheNinth** [comment]
Duplicate of #83. This is an issue in Enchancement, not Balm.
